services:
  db:
    env_file:
      - ./backend/.env.production
    ports: []
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env.production
    environment:
      APP_ENV: production
      POSTGRES_HOST: db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
    env_file:
      - ./frontend/.env.production
    environment:
      APP_ENV: production
      NODE_ENV: production
    restart: always
